name: Build

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master, workflow ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        #goos: ['aix', 'android', 'darwin', 'dragonfly', 'freebsd', 'illumos', 'js', 'linux', 'netbsd', 'openbsd', 'plan9', 'solaris', 'window']
        #goarch: [ '386', 'amd64', 'arm', 'arm64', 'ppc64', 'ppc64le', 'mips', 'mipsle', 'mips64', 'mips64le', 'riscv64', 's390x', 'wasm' ]
        goos: ['linux']
        goarch: ['amd64', 'arm64']

    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:   
    - name: Install Go
      id: install_go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
#     - name: Setup Cache
#       uses: actions/cache@v2
#       with:
#         path: ${{ steps.install_go.outputs.go_cache }}
#         key: cross-build-go${{ matrix.go }}-${{ matrix.goos }}-${{ hashFiles('**/go.sum') }}
#         restore-keys: |
#           cross-build-go${{ matrix.go }}-${{ matrix.goos }}

    - name: Prepare UPX
      run: |
        sudo apt update
        sudo apt install upx
        echo "::set-output name=go_cache::$(go env GOCACHE)"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Client
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        LDFLAGS: "-X github.com/lflare/mdathome-golang/internal/mdathome.ClientVersion=${GITHUB_REF}" 
      run: |
        go build -o ./mdathome-${{ github.ref }}-${{ matrix.goos }}-${{ matrix.goarch }} -tags netgo -trimpath -ldflags=${LDFLAGS} ./cmd/mdathome
