name: Build

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master, workflow ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Prepare Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare GoReleaser
      run: go get github.com/goreleaser/goreleaser
    
    - name: Prepare UPX
      run: |
        apt update
        apt install upx

    - name: Build
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
