name: Build

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master, workflow ]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        goos: ['aix', 'android', 'darwin', 'dragonfly', 'freebsd', 'illumos', 'js', 'linux', 'netbsd', 'openbsd', 'plan9', 'solaris', 'window']
        goarch: [ '386', 'amd64', 'arm', 'arm64', 'ppc64', 'ppc64le', 'mips', 'mipsle', 'mips64', 'mips64le', 'riscv64', 's390x', 'wasm' ]

    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:   
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare UPX
      run: |
        sudo apt update
        sudo apt install upx

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Client
      env:
        CGO_ENABLED: 0
        LDFLAGS: "-X github.com/lflare/mdathome-golang/internal/mdathome.ClientVersion=${GITHUB_REF##*/} -X mdathome.Build=${GITHUB_SHA}" 
      run: |
        go build -o ./mdathome-golang -tags netgo -trimpath -ldflags=${LDFLAGS} ./cmd/mdathome
